"""Generate PipeWire configuration files from Tonal state."""

import os
import shutil
import datetime
import logging
from constants import (
    PIPEWIRE_CONF_DIR, PULSE_CONF_DIR, ROUTING_CONF, PULSE_CONF,
    TYPE_TO_PIPEWIRE, TARGET_EXPANDED, TARGET_USB1_CHAT, TARGET_USB2,
    PREAMP_SHELF_FREQ,
)
from eq_math import clamp_bands
from state import resolve_expanded_target

log = logging.getLogger("tonal.config")

def _backup(path):
    if os.path.exists(path):
        bak = path + ".bak"
        shutil.copy2(path, bak)
        log.info("Backed up %s → %s", path, bak)


def _eq_nodes_and_links(preamp_db, bands):
    nodes = [f'                    {{ type = builtin name = preamp label = bq_highshelf '
             f'control = {{ "Freq" = {PREAMP_SHELF_FREQ} "Q" = 0.707 "Gain" = {preamp_db} }} }}']
    links = []
    prev = "preamp"
    for i, band in enumerate(bands):
        name = f"eq{i:02d}"
        label = TYPE_TO_PIPEWIRE.get(band["type"], "bq_peaking")
        nodes.append(f'                    {{ type = builtin name = {name} label = {label} '
                     f'control = {{ "Freq" = {band["freq"]} "Q" = {band["q"]} "Gain" = {band["gain"]} }} }}')
        links.append(f'                    {{ output = "{prev}:Out" input = "{name}:In" }}')
        prev = name
    return "\n".join(nodes), "\n".join(links)


def _filter_chain(description, node_name, target, position, preamp_db, bands, dont_remix=False):
    nodes_str, links_str = _eq_nodes_and_links(preamp_db, bands)
    pos_str = "[ " + " ".join(position) + " ]"
    remix = "\n                stream.dont-remix = true" if dont_remix else ""

    # flags = [ nofail ]: a filter chain that fails to build must not abort
    # PipeWire startup. Without it, one bad graph takes down the whole daemon —
    # and with it xdg-desktop-portal, which makes every GTK app hang on startup.
    return f"""    {{ name = libpipewire-module-filter-chain
        flags = [ nofail ]
        args = {{
            node.description = "{description}"
            media.name       = "{description}"
            filter.graph = {{
                nodes = [
{nodes_str}
                ]
                links = [
{links_str}
                ]
            }}
            capture.props = {{
                node.name        = "{node_name}"
                media.class      = Audio/Sink
                audio.channels   = 2
                audio.position   = [ FL FR ]
            }}
            playback.props = {{
                node.name        = "{node_name}_out"
                target.object    = "{target}"
                audio.channels   = 2
                audio.position   = {pos_str}{remix}
                node.passive     = true
            }}
        }}
    }}"""


def generate_routing_conf(state):
    hw = state["hardware"]
    channels = state["channels"]
    eq = state["eq"]
    profile_name = eq["active_profile"]
    profile = eq["profiles"].get(profile_name, {"preamp_db": 0, "bands": []})
    preamp_db = profile["preamp_db"] if eq["enabled"] else 0.0
    if eq["enabled"]:
        bands = profile["bands"]
    else:
        # Keep band nodes in the filter chain but zero all gains, so the
        # node infrastructure stays in place for live EQ updates when re-enabled.
        bands = [{"freq": b["freq"], "q": b["q"], "gain": 0.0, "type": b["type"]}
                 for b in profile["bands"]]

    # Safety net: no biquad below the audible floor ever reaches PipeWire,
    # whatever the profile source. See constants.MIN_BAND_FREQ.
    bands = clamp_bands(bands)

    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Only include the ALSA adapter if we have expanded channels
    has_expanded = any(ch["target"] == TARGET_EXPANDED for ch in channels if ch["enabled"])

    lines = [
        f"# RODECaster Pro II — Multi-Channel Routing with Per-Channel EQ",
        f"# Generated by Tonal on {ts}",
        f"# Profile: {profile_name} | Pre Amp: {preamp_db} dB | Bands: {len(bands)}",
        f"# DO NOT EDIT — regenerated by Tonal. Backup: .bak",
        f"# Every block below is flagged nofail: if a device is missing, that sink",
        f"# is skipped and PipeWire still starts normally.",
        f"",
    ]

    if has_expanded:
        # Re-resolve the ALSA path here rather than trusting state["hardware"],
        # which may have been detected minutes or reboots ago. Card numbers are
        # assigned by USB enumeration order, so the index that was correct when
        # the user last opened Tonal is not necessarily correct now.
        #
        # An unresolvable api.alsa.path is not a cosmetic problem: this block
        # lives in context.objects, which PipeWire builds during context
        # creation, so a miss makes the daemon exit -EINVAL before it loads a
        # single module. That takes xdg-desktop-portal with it and every GTK app
        # then blocks ~25s per settings lookup at startup. Hence two guards:
        # verify the PCM exists before writing, and mark the object nofail so a
        # later hardware change degrades to a missing sink instead of no audio
        # subsystem at all.
        expanded = resolve_expanded_target()
        if expanded is None:
            log.warning("Expanded channels are enabled but no 10-channel PCM is "
                        "present — omitting the ALSA adapter. Check that USB 1 is "
                        "connected and the RODECaster is in Expanded mode.")
        else:
            alsa_card, alsa_dev, alsa_ch = expanded
            lines.extend([
                f"context.objects = [",
                f"    {{ factory = adapter",
                f"        flags = [ nofail ]",
                f"        args = {{",
                f'            factory.name           = api.alsa.pcm.sink',
                f'            node.name              = "rodecaster_expanded"',
                f'            node.description       = "RODECaster Expanded"',
                f'            media.class            = Audio/Sink',
                f'            api.alsa.path          = "hw:{alsa_card},{alsa_dev}"',
                f"            audio.channels         = {alsa_ch}",
                f"            audio.position         = [ FL FR FC LFE RL RR FLC FRC RC SL ]",
                f"            audio.format           = S32LE",
                f"            audio.rate             = 48000",
                f"            session.suspend-timeout-seconds = 0",
                f"        }}",
                f"    }}",
                f"]",
                f"",
            ])

    lines.append("context.modules = [")

    for ch in channels:
        if not ch["enabled"]:
            continue

        # Resolve target to actual PipeWire node name
        if ch["target"] == TARGET_EXPANDED:
            target = "rodecaster_expanded"
            dont_remix = ch["position"] != ["FL", "FR"]
        elif ch["target"] == TARGET_USB1_CHAT:
            target = hw.get("usb1_chat_node", "")
            if not target:
                log.warning("USB 1 Chat node not detected, skipping channel '%s'", ch["name"])
                continue
            dont_remix = False
        elif ch["target"] == TARGET_USB2:
            target = hw.get("usb2_node", "")
            if not target:
                log.warning("USB 2 node not detected, skipping channel '%s'", ch["name"])
                continue
            dont_remix = False
        else:
            target = ch["target"]
            dont_remix = False

        lines.append(f"\n    # ── {ch['name']} ({' '.join(ch['position'])}) ──")
        lines.append(_filter_chain(ch["name"], ch["node"], target, ch["position"],
                                    preamp_db, bands, dont_remix))

    lines.append("]")
    return "\n".join(lines)


def generate_pulse_rules_conf(state):
    rules = state["routing"]["rules"]
    ch_map = {ch["name"]: ch["node"] for ch in state["channels"]}
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        f"# Per-App Routing Rules — Generated by Tonal on {ts}",
        f"# DO NOT EDIT — regenerated by Tonal. Backup: .bak",
        f"",
        f"pulse.rules = [",
    ]
    for rule in rules:
        node = ch_map.get(rule["channel"], "system_eq")
        key = "application.process.binary" if rule.get("binary") else "application.name"
        val = rule.get("binary", rule["app"])
        lines.append(f"    # {rule['app']} → {rule['channel']}")
        lines.append(f"    {{")
        lines.append(f'        matches = [ {{ {key} = "{val}" }} ]')
        lines.append(f'        actions = {{ update-props = {{ target.object = "{node}" }} }}')
        lines.append(f"    }}")
    lines.append("]")
    return "\n".join(lines)


def write_configs(state):
    os.makedirs(PIPEWIRE_CONF_DIR, exist_ok=True)
    os.makedirs(PULSE_CONF_DIR, exist_ok=True)
    _backup(ROUTING_CONF)
    _backup(PULSE_CONF)
    with open(ROUTING_CONF, "w") as f:
        f.write(generate_routing_conf(state))
    log.info("Wrote %s", ROUTING_CONF)
    with open(PULSE_CONF, "w") as f:
        f.write(generate_pulse_rules_conf(state))
    log.info("Wrote %s", PULSE_CONF)
    return ROUTING_CONF, PULSE_CONF
